#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
find $DOTFILES_ROOT/.setup/ -type f -iname "*.sh" -exec chmod +x {} \;
source $DOTFILES_ROOT/.setup/functions.sh

plus 'initial setup'

.setup/installs/macos-defaults.sh
.setup/installs/omzsh.sh
.setup/installs/dotfiles.sh
.setup/installs/utilities/install.sh
.setup/installs/homebrew/install.sh
.setup/installs/hammerspoon.sh
.setup/installs/vscode/install.sh

info 'updating configuration'
cd $DOTFILES_ROOT && git pull && git submodule update --init --recursive

if test "$(uname)" = "Darwin"
then
	info 'launching Hammerspoon'
	open -a Hammerspoon
fi

minus 'setup finished'

exit 0
