#!/usr/bin/env bash
#
# Initial setup

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

plus () {
  printf "\r  [ \033[0;33m++\033[0m ] $1\n"
}

minus () {
  printf "\r  [ \033[0;31m--\033[0m ] $1\n"
}

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r  [ \033[0;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r  [ \033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_utils () {
  info 'installing utility repos'

  declare -a repos=(
    "git@gitlab.com:rsefer/server-scripts.git"
  )
  cd "$HOME"
  UTILS_DIR="utils"

	if [ ! -d "$UTILS_DIR" ]; then
		mkdir "$UTILS_DIR"
	fi
  cd "$UTILS_DIR"
  for repo in "${repos[@]}"
  do
    basename=$(basename "$repo")
    filename=${basename%.*}
    if [ ! -d "$filename" ]; then
  		git clone "$repo"
      success "cloned util $repo"
    else
      success "skipped cloning $repo"
  	fi
  done
}

install_homebrew () {
  if test ! $(which brew)
  then
    info 'installing Homebrew'
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if test $(which brew)
  then
    info 'installing brew bundle from Brewfile'
  	cd "$DOTFILES_ROOT/.setup"
  	brew bundle
  fi
}

install_omzsh () {
  info 'installing Oh My ZSH'
  chsh -s $(which zsh)
  sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
}

echo ''
plus 'Initial Setup'
echo ''
install_dotfiles
echo ''
install_utils
echo ''
install_homebrew
echo ''
install_omzsh
echo ''
minus 'Setup Finished'
echo ''

exit 0
