// See https://hyper.is#cfg for all currently supported options.

module.exports = {
	config: {
		updateChannel: 'stable',
		fontSize: 18,
		fontFamily: 'SF Mono, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
		fontWeight: 'normal',
		fontWeightBold: 'bold',
		lineHeight: 1,
		letterSpacing: 0,
		cursorColor: 'rgba(255,255,255,0.8)',
		cursorAccentColor: '#000',
		cursorShape: 'BLOCK',
		cursorBlink: false,
		foregroundColor: '#fff',
		backgroundColor: '#1D1D1D',
		selectionColor: 'rgba(55,25,0.3)',
		borderColor: '#333',
		css: '',
		termCSS: '',
		showHamburgerMenu: '',
		showWindowControls: '',
		padding: '12px 14px',
		colors: {
			black: '#000000',
			red: '#C51E14',
			green: '#1DC121',
			yellow: '#C7C329',
			blue: '#0A2FC4',
			magenta: '#C839C5',
			cyan: '#20C5C6',
			white: '#C7C7C7',
			lightBlack: '#686868',
			lightRed: '#FD6F6B',
			lightGreen: '#67F86F',
			lightYellow: '#FFFA72',
			lightBlue: '#6A76FB',
			lightMagenta: '#FD7CFC',
			lightCyan: '#68FDFE',
			lightWhite: '#FFFFFF',
		},
		scrollbarOpacity: 0.5,
		shell: '',
		shellArgs: ['--login'],
		env: {},
		bell: 'SOUND',
		copyOnSelect: false,
		defaultSSHApp: true,
		quickEdit: false,
		macOptionSelectionMode: 'vertical',
		webGLRenderer: true,
		hyperTabs: {
			border: true,
			tabIconsColored: true
		}
	},
	plugins: [
        "hypercwd",
        "hyper-pane",
        "hyper-filedrop",
        "hyper-single-instance",
        "hyper-fading-scrollbar",
        "hyper-tabs-enhanced"
    ],
	localPlugins: [],
	keymaps: {},
};
