#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
find $DOTFILES_ROOT/setup/ -type f -iname "*.sh" -exec chmod +x {} \;
find $DOTFILES_ROOT/bin/ -type f -iname "*" -exec chmod +x {} \;
source $DOTFILES_ROOT/setup/functions.sh

plus 'initial setup'

setup/installs/omzsh.sh

if test "$(uname)" = "Darwin"
then
	setup/installs/hammerspoon.sh
	setup/installs/homebrew/install.sh
	setup/installs/vscode/install.sh
	setup/installs/macos/install.sh
fi

setup/installs/dotfiles.sh

. $HOME/.zshrc

if test "$(uname)" = "Darwin"
then
	info 'launching Hammerspoon'
	open -a Hammerspoon
fi

setup/installs/utilities/install.sh

minus 'setup finished'

exit 0
