#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
find $DOTFILES_ROOT/setup/ -type f -iname "*.sh" -exec chmod +x {} \;
find $DOTFILES_ROOT/bin/ -type f -iname "*" -exec chmod +x {} \;
source $DOTFILES_ROOT/setup/functions.sh

plus 'initial setup'

if test "$(uname)" = "Darwin"; then
	setup/installs/homebrew/install.sh
	setup/installs/hammerspoon.sh
	setup/installs/obsidian.sh
	setup/installs/vscode/install.sh
	setup/installs/macos/install.sh
fi

setup/installs/dotfiles.sh
setup/installs/utilities/install.sh

if test "$(uname)" = "Darwin"; then
	info 'launching Hammerspoon'
	open -a Hammerspoon
	info 'launching Raycast'
	open -a Raycast
fi

minus 'setup finished'

. $HOME/.zshrc

exit 0
